apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: cluster-dev-eks
spec:
  id: cluster-dev-eks
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    minNodeCount: 2
  writeConnectionSecretToRef:
    name: cluster-dev-eks
