apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: cluster-prod-eks
spec:
  id: cluster-prod-eks
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    minNodeCount: 1
  writeConnectionSecretToRef:
    name: cluster-prod-eks
